### ISSUE TITLE
Can we use it for localization also?

### ISSUE THREAD

**Issue by mjza** [Innofactor/EfCoreJsonValueConverter#11]
Hi there, this is not an issue and more a question!

Do you think it is possible to use this library for localization?

I asked a question [here](https://stackoverflow.com/questions/63203219/how-can-i-implement-localization-as-a-json-object-in-a-net-ef-core), and I think it is possible to extend your library for this use-case!

**Comment by AlexEngblom** [comment]
I suppose you could accomplish it by using this library together with JsonConverter attribute and custom converter to do the localization mapping without any special extension for this library itself. 

[This old issue](https://github.com/Innofactor/EfCoreJsonValueConverter/issues/3) has some discussion about using them and a commit link showcasing its use in a unit test.
