### ISSUE TITLE
Entity Framework Core 6.0 (NET 6) support

### ISSUE THREAD

**Issue by romanov** [Innofactor/EfCoreJsonValueConverter#15]
After upgrading the project to NET 6 i've got:
`MissingMethodException: Method not found: 'System.Type Microsoft.EntityFrameworkCore.Metadata.ITypeBase.get_ClrType()'.`

Maybe, the problem is with Entity Framework Core 6

**Comment by rstefek** [comment]
Same here after update to EFCore 6:

```
MissingMethodException: Method not found: 'System.Type Microsoft.EntityFrameworkCore.Metadata.ITypeBase.get_ClrType()'.
Innofactor.EfCoreJsonValueConverter.ModelBuilderExtensions.AddJsonFields(ModelBuilder modelBuilder, bool skipConventionalEntities)
```

**Comment by scetu** [comment]
Same problem after today upgrade of our app to .NET 6.

`MissingMethodException: Method not found: 'System.Type Microsoft.EntityFrameworkCore.Metadata.ITypeBase.get_ClrType()'.
`

**Comment by rstefek** [comment]
Solved temporarily by downloading repo, adding manually to our project and updated EFCore to 6.0.0 and target to net6.0

Then it worked like a charm without any code change. I was surprised by this :)

Updated .csproj file:
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <Authors>Innofactor</Authors>
    <Company>Innofactor</Company>
    <Description>JSON value converter for Entity Framework Core 3.0+</Description>
    <PackageLicenseUrl>https://github.com/Innofactor/EfCoreJsonValueConverter/blob/master/LICENSE</PackageLicenseUrl>
    <PackageProjectUrl>https://github.com/Innofactor/EfCoreJsonValueConverter</PackageProjectUrl>
    <PackageIconUrl>http://rappen.net/Cinteros/innofactor.png</PackageIconUrl>
    <RepositoryUrl>https://github.com/Innofactor/EfCoreJsonValueConverter</RepositoryUrl>
    <SignAssembly>true</SignAssembly>
    <AssemblyOriginatorKeyFile>signkey.snk</AssemblyOriginatorKeyFile>
    <DelaySign>false</DelaySign>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Innofactor.EfCoreJsonValueConverter.Attributes" Version="2.0.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="6.0.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.1" />
  </ItemGroup>

</Project>
```

**Comment by scetu** [comment]
@rstefek you could make a pull request to this repo, but dunno know if it even maintained by somebody anymore.

**Comment by joelcoxokc** [comment]
@AlexEngblom @jukkahyv 
Are yall still maintaining this package?
The PR for this issue works fine. 

Our team is unable to update to 6.0 because MS has not released documentation on doing JSON columns and this package needs to be updated.

**Comment by AlexEngblom** [comment]
> @AlexEngblom @jukkahyv Are yall still maintaining this package? The PR for this issue works fine.
> 
> Our team is unable to update to 6.0 because MS has not released documentation on doing JSON columns and this package needs to be updated.

Thanks for your activity on the issue. Been slacking on the maintenance here for sure, sorry about that. New NuGet package for .NET 6.0 is published now, bumping up to match the version number with .NET: https://www.nuget.org/packages/Innofactor.EfCoreJsonValueConverter/6.0.0
